#!/usr/bin/env node
/**
 * Builds a fully self-contained webgame/index.html for the React Native WebView.
 *
 * React Native does not bundle sibling assets referenced by App.js — only the
 * single .html you `require` gets packaged. So three.min.js, game.js and
 * mobile-controls.js are inlined into one file. </script> sequences inside the
 * JS sources are escaped to keep the document valid.
 *
 * Also emits webgame/index.html.js — the same document exported as a JS string
 * module so App.js can pass it to WebView as source={{ html: ... }} in both dev
 * and production APK builds.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const indexHtml = resolve(root, 'index.html');
const outDir = resolve(root, 'webgame');
const outFile = resolve(outDir, 'index.html');
const strOutFile = resolve(outDir, 'index.html.js');

const bundles = ['three.min.js', 'game.js', 'mobile-controls.js'];
const srcre = /<script[^>]*src=["']([^"']+\.js)["'][^>]*>\s*<\/script>/g;

let html = readFileSync(indexHtml, 'utf8');

// Drop external resources (e.g. Google Fonts) so the WebView bundle works fully
// offline and the window "load" event is never blocked by the network.
const externalLink = /<link[^>]*\bhref=["']https?:\/\/[^"']+["'][^>]*>/gi;
html = html.replace(externalLink, '');

let inlined = [];
html = html.replace(srcre, (full, src) => {
  if (!bundles.includes(src)) {
    throw new Error(`Unexpected external script "${src}" in index.html`);
  }
  inlined.push(src);
  return `<!-- inlined: ${src} -->`;
});

if (inlined.length !== bundles.length) {
  throw new Error(`Expected to inline ${bundles.length} scripts, found ${inlined.length}`);
}

const replacements = inlined
  .map((src) => {
    const code = readFileSync(resolve(root, src), 'utf8').replace(/<\/script/gi, '<\\/script');
    return `<script>/* ${src} */\n${code}\n</script>`;
  })
  .join('\n');

// IMPORTANT: use a function replacement, NOT a string replacement. game.js
// contains many `$'`, `$$`, `$&` and `$` sequences inside its own template
// literals; String.prototype.replace scans a string replacement for those
// special `$` patterns (e.g. `$'` = "text after the match") and would corrupt
// the inlined code, producing a SyntaxError in the WebView.
html = html.replace('</body>', () => `${replacements}\n</body>`);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, html);

// String module for App.js (production-safe; bypasses Metro's html asset
// mechanism which resolves to a broken uri in release builds).
// ESM default export — package.json declares "type": "module", so Metro treats
// .js files as ESM and a CJS `module.exports` would not be picked up.
const asJsString = JSON.stringify(html)
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029')
  .replace(/<\/script/gi, '<\\/script');
writeFileSync(strOutFile, `// Generated by scripts/build-webview.mjs — do not edit.\nexport default ${asJsString};\n`);

console.log(`webgame/index.html written (${(html.length / 1024).toFixed(0)} KB, ${bundles.length} scripts inlined)`);
console.log(`webgame/index.html.js written (${(asJsString.length / 1024).toFixed(0)} KB string module)`);